# Form implementation generated from reading ui file 'NotesWidget.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_widget_Notes(object):
    def setupUi(self, widget_Notes):
        widget_Notes.setObjectName("widget_Notes")
        widget_Notes.resize(222, 194)
        self.gridLayout_2 = QtWidgets.QGridLayout(widget_Notes)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textEdit_Notes = QtWidgets.QTextEdit(parent=widget_Notes)
        self.textEdit_Notes.setSizeIncrement(QtCore.QSize(1, 1))
        self.textEdit_Notes.setMarkdown("")
        self.textEdit_Notes.setHtml("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>")
        self.textEdit_Notes.setTabStopDistance(20.0)
        self.textEdit_Notes.setObjectName("textEdit_Notes")
        self.gridLayout_2.addWidget(self.textEdit_Notes, 0, 1, 1, 1)

        self.retranslateUi(widget_Notes)
        QtCore.QMetaObject.connectSlotsByName(widget_Notes)

    def retranslateUi(self, widget_Notes):
        _translate = QtCore.QCoreApplication.translate
        widget_Notes.setWindowTitle(_translate("widget_Notes", "Notes"))
        self.textEdit_Notes.setPlaceholderText(_translate("widget_Notes", "Enter your notes here"))
